# Problem 2
# https://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Answer: evenfibsum(4e6)

evenfibsum <- function(max){
  fib <- matrix(0)
  fib[[1]] <- 1
  fib[[2]] <- 2
  for (i in 3:max){     
    if ((fib[[i-1]] + fib[[i-2]]) > max) break
    fib[[i]] <- fib[[i-1]] + fib[[i-2]]    
  }
  return(sum(fib[fib%%2==0]))
}
